# custom
language: python
sudo: false

python:
    - 2.7

env:
    - ENVIRON=py
      TOXENV=py27
    - ENVIRON=code-conventions
      TOXENV=isort,flake8,code-analysis


before_install:
    - mkdir -p $HOME/buildout-cache/{eggs,downloads}
    - mkdir $HOME/.buildout
    - echo "[buildout]" > $HOME/.buildout/default.cfg
    - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
    - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg

install:
    - travis_retry pip install -U setuptools==33.1.1 tox coveralls coverage

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
    pip: true
    directories:
      - eggs/
      - $HOME/eggs/
      - $HOME/buildout-cache
