# custom
language: python
sudo: false

matrix:
    include:
        - python: "2.7"
          env: TOXENV=py27,isort,flake8

install:
    - pip install -U setuptools==33.1.1 tox coveralls coverage
    - python bootstrap-buildout.py
    - bin/buildout

script:
    #- coverage run bin/test -v1
    - tox
after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
    pip: true
    directories:
      - eggs/
